/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'njallzzz' at '10/19/16 5:01 PM' with Gradle 3.1
 *
 * @author njallzzz, @date 10/19/16 5:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
